trigger:
- test

pool: dev-3

variables:
  - group: varstest

steps:
- script: |
    touch .env.local
    sed -i '/AUTH0_SECRET/c\AUTH0_SECRET=$(AUTH0_SECRET)' .env.local
    sed -i '/AUTH0_BASE_URL/c\AUTH0_BASE_URL=$(AUTH0_BASE_URL)' .env.local
    sed -i '/AUTH0_ISSUER_BASE_URL/c\AUTH0_ISSUER_BASE_URL=$(AUTH0_ISSUER_BASE_URL)' .env.local
    sed -i '/AUTH0_CLIENT_ID/c\AUTH0_CLIENT_ID=$(AUTH0_CLIENT_ID)' .env.local
    sed -i '/NEXT_PUBLIC_BASE_URL/c\NEXT_PUBLIC_BASE_URL=$(NEXT_PUBLIC_BASE_URL)' .env.local
    sed -i '/AUTH0_CLIENT_SECRET/c\AUTH0_CLIENT_SECRET=$(AUTH0_CLIENT_SECRET)' .env.local
    sed -i '/NEXT_PUBLIC_API_URL/c\NEXT_PUBLIC_API_URL=https://synkaa-test-api.symple.co.in/synkaa-app/api' .env.local  
    sed -i '/NEXT_PUBLIC_SOCKET_URL/c\NEXT_PUBLIC_SOCKET_URL=$(NEXT_PUBLIC_SOCKET_URL)' .env.local  
    
    cat .env.local
    docker build -f devops/Dockerfile -t $(imageName) .
    docker stop $(imageName) &> /dev/null && docker rm $(imageName) &> /dev/null && echo "image stopped"
    docker run -d  --name $(imageName) -p 8509:3000 $(imageName)
